/*EASY: Using jQuery's AJAX functions, create a page that will display the names of the people currently in space,
as well as what spacecraft they are currently on. API Documentation: http://open-notify.org/*/


var space =
[
    {
        "people": [
            { "craft": "ISS", "name": "Oleg Artemyev" },
            { "craft": "ISS", "name": "Andrew Feustel" },
            { "craft": "ISS", "name": "Richard Arnold" },
            { "craft": "ISS", "name": "Sergey Prokopyev" },
            { "craft": "ISS", "name": "Alexander Gerst" },
            { "craft": "ISS", "name": "Serena Aunon-Chancellor" }
        ],
        "number": 6
    }
]
console.log(space);

