/*MEDIUM: Using a weather API, fetch and display weather for Charlotte to a webpage that you create.
You should display at a minimum the current temperature and sky conditions.
This API: https://openweathermap.org/current is free. It just requires an account be created.
You can browse other weather APIs if you would like to use something else.*/


/*MEDIUM PT. 2: Add an input field and button on your page that let's the user enter a city
and update the weather to the city of their choosing. Handle errors if a user enters bad input.*/

